#include "modules/imgui/imgui_enums.h"
#include "sol_ext.h"

void solus::modules::imgui_module::initialize_enums(sol::table &mod) {
  
#pragma region enums
mod.new_enum("ImGuiWindowFlags", ENUM_HELPER(ImGuiWindowFlags, None),
             ENUM_HELPER(ImGuiWindowFlags, NoTitleBar),
             ENUM_HELPER(ImGuiWindowFlags, NoResize),
             ENUM_HELPER(ImGuiWindowFlags, NoMove),
             ENUM_HELPER(ImGuiWindowFlags, NoScrollbar),
             ENUM_HELPER(ImGuiWindowFlags, NoScrollWithMouse),
             ENUM_HELPER(ImGuiWindowFlags, NoCollapse),
             ENUM_HELPER(ImGuiWindowFlags, AlwaysAutoResize),
             ENUM_HELPER(ImGuiWindowFlags, NoBackground),
             ENUM_HELPER(ImGuiWindowFlags, NoSavedSettings),
             ENUM_HELPER(ImGuiWindowFlags, NoMouseInputs),
             ENUM_HELPER(ImGuiWindowFlags, MenuBar),
             ENUM_HELPER(ImGuiWindowFlags, HorizontalScrollbar),
             ENUM_HELPER(ImGuiWindowFlags, NoFocusOnAppearing),
             ENUM_HELPER(ImGuiWindowFlags, NoBringToFrontOnFocus),
             ENUM_HELPER(ImGuiWindowFlags, AlwaysVerticalScrollbar),
             ENUM_HELPER(ImGuiWindowFlags, AlwaysHorizontalScrollbar),
             ENUM_HELPER(ImGuiWindowFlags, NoNavInputs),
             ENUM_HELPER(ImGuiWindowFlags, NoNavFocus),
             ENUM_HELPER(ImGuiWindowFlags, UnsavedDocument),
             ENUM_HELPER(ImGuiWindowFlags, NoDocking),
             ENUM_HELPER(ImGuiWindowFlags, NoNav),
             ENUM_HELPER(ImGuiWindowFlags, NoDecoration),
             ENUM_HELPER(ImGuiWindowFlags, NoInputs),
             ENUM_HELPER(ImGuiWindowFlags, NavFlattened),
             ENUM_HELPER(ImGuiWindowFlags, ChildWindow),
             ENUM_HELPER(ImGuiWindowFlags, Tooltip),
             ENUM_HELPER(ImGuiWindowFlags, Popup),
             ENUM_HELPER(ImGuiWindowFlags, Modal),
             ENUM_HELPER(ImGuiWindowFlags, ChildMenu),
             ENUM_HELPER(ImGuiWindowFlags, DockNodeHost),
             ENUM_HELPER(ImGuiWindowFlags, NoNavFocus));
mod.new_enum("ImGuiChildFlags", ENUM_HELPER(ImGuiChildFlags, None),
             ENUM_HELPER(ImGuiChildFlags, Border),
             ENUM_HELPER(ImGuiChildFlags, AlwaysUseWindowPadding),
             ENUM_HELPER(ImGuiChildFlags, ResizeX),
             ENUM_HELPER(ImGuiChildFlags, ResizeY),
             ENUM_HELPER(ImGuiChildFlags, AutoResizeX),
             ENUM_HELPER(ImGuiChildFlags, AutoResizeY),
             ENUM_HELPER(ImGuiChildFlags, AlwaysAutoResize),
             ENUM_HELPER(ImGuiChildFlags, FrameStyle));
mod.new_enum("ImGuiInputTextFlags", ENUM_HELPER(ImGuiInputTextFlags, None),
             ENUM_HELPER(ImGuiInputTextFlags, CharsDecimal),
             ENUM_HELPER(ImGuiInputTextFlags, CharsHexadecimal),
             ENUM_HELPER(ImGuiInputTextFlags, CharsUppercase),
             ENUM_HELPER(ImGuiInputTextFlags, CharsNoBlank),
             ENUM_HELPER(ImGuiInputTextFlags, AutoSelectAll),
             ENUM_HELPER(ImGuiInputTextFlags, EnterReturnsTrue),
             ENUM_HELPER(ImGuiInputTextFlags, CallbackCompletion),
             ENUM_HELPER(ImGuiInputTextFlags, CallbackHistory),
             ENUM_HELPER(ImGuiInputTextFlags, CallbackAlways),
             ENUM_HELPER(ImGuiInputTextFlags, CallbackCharFilter),
             ENUM_HELPER(ImGuiInputTextFlags, AllowTabInput),
             ENUM_HELPER(ImGuiInputTextFlags, CtrlEnterForNewLine),
             ENUM_HELPER(ImGuiInputTextFlags, NoHorizontalScroll),
             ENUM_HELPER(ImGuiInputTextFlags, ReadOnly),
             ENUM_HELPER(ImGuiInputTextFlags, Password),
             ENUM_HELPER(ImGuiInputTextFlags, NoUndoRedo),
             ENUM_HELPER(ImGuiInputTextFlags, CharsScientific),
             ENUM_HELPER(ImGuiInputTextFlags, CallbackResize),
             ENUM_HELPER(ImGuiInputTextFlags, CallbackEdit));
mod.new_enum("ImGuiTreeNodeFlags", ENUM_HELPER(ImGuiTreeNodeFlags, None),
             ENUM_HELPER(ImGuiTreeNodeFlags, Selected),
             ENUM_HELPER(ImGuiTreeNodeFlags, Framed),
             ENUM_HELPER(ImGuiTreeNodeFlags, AllowOverlap),
             ENUM_HELPER(ImGuiTreeNodeFlags, NoTreePushOnOpen),
             ENUM_HELPER(ImGuiTreeNodeFlags, NoAutoOpenOnLog),
             ENUM_HELPER(ImGuiTreeNodeFlags, DefaultOpen),
             ENUM_HELPER(ImGuiTreeNodeFlags, OpenOnDoubleClick),
             ENUM_HELPER(ImGuiTreeNodeFlags, OpenOnArrow),
             ENUM_HELPER(ImGuiTreeNodeFlags, Leaf),
             ENUM_HELPER(ImGuiTreeNodeFlags, Bullet),
             ENUM_HELPER(ImGuiTreeNodeFlags, FramePadding),
             ENUM_HELPER(ImGuiTreeNodeFlags, SpanAvailWidth),
             ENUM_HELPER(ImGuiTreeNodeFlags, SpanFullWidth),
             ENUM_HELPER(ImGuiTreeNodeFlags, SpanTextWidth),
             ENUM_HELPER(ImGuiTreeNodeFlags, SpanAllColumns),
             ENUM_HELPER(ImGuiTreeNodeFlags, NavLeftJumpsBackHere),
             ENUM_HELPER(ImGuiTreeNodeFlags, CollapsingHeader));
mod.new_enum("ImGuiPopupFlags", ENUM_HELPER(ImGuiPopupFlags, None),
             ENUM_HELPER(ImGuiPopupFlags, MouseButtonLeft),
             ENUM_HELPER(ImGuiPopupFlags, MouseButtonRight),
             ENUM_HELPER(ImGuiPopupFlags, MouseButtonMiddle),
             ENUM_HELPER(ImGuiPopupFlags, MouseButtonMask_),
             ENUM_HELPER(ImGuiPopupFlags, MouseButtonDefault_),
             ENUM_HELPER(ImGuiPopupFlags, NoReopen),
             ENUM_HELPER(ImGuiPopupFlags, NoOpenOverExistingPopup),
             ENUM_HELPER(ImGuiPopupFlags, NoOpenOverItems),
             ENUM_HELPER(ImGuiPopupFlags, AnyPopupId),
             ENUM_HELPER(ImGuiPopupFlags, AnyPopupLevel),
             ENUM_HELPER(ImGuiPopupFlags, AnyPopup));
mod.new_enum("ImGuiSelectableFlags", ENUM_HELPER(ImGuiSelectableFlags, None),
             ENUM_HELPER(ImGuiSelectableFlags, DontClosePopups),
             ENUM_HELPER(ImGuiSelectableFlags, SpanAllColumns),
             ENUM_HELPER(ImGuiSelectableFlags, AllowDoubleClick),
             ENUM_HELPER(ImGuiSelectableFlags, Disabled),
             ENUM_HELPER(ImGuiSelectableFlags, AllowOverlap));
mod.new_enum("ImGuiComboFlags", ENUM_HELPER(ImGuiComboFlags, None),
             ENUM_HELPER(ImGuiComboFlags, PopupAlignLeft),
             ENUM_HELPER(ImGuiComboFlags, HeightSmall),
             ENUM_HELPER(ImGuiComboFlags, HeightRegular),
             ENUM_HELPER(ImGuiComboFlags, HeightLarge),
             ENUM_HELPER(ImGuiComboFlags, HeightLargest),
             ENUM_HELPER(ImGuiComboFlags, NoArrowButton),
             ENUM_HELPER(ImGuiComboFlags, NoPreview),
             ENUM_HELPER(ImGuiComboFlags, HeightMask_));
mod.new_enum("ImGuiTabBarFlags", ENUM_HELPER(ImGuiTabBarFlags, None),
             ENUM_HELPER(ImGuiTabBarFlags, Reorderable),
             ENUM_HELPER(ImGuiTabBarFlags, AutoSelectNewTabs),
             ENUM_HELPER(ImGuiTabBarFlags, TabListPopupButton),
             ENUM_HELPER(ImGuiTabBarFlags, NoCloseWithMiddleMouseButton),
             ENUM_HELPER(ImGuiTabBarFlags, NoTabListScrollingButtons),
             ENUM_HELPER(ImGuiTabBarFlags, NoTooltip),
             ENUM_HELPER(ImGuiTabBarFlags, FittingPolicyResizeDown),
             ENUM_HELPER(ImGuiTabBarFlags, FittingPolicyScroll),
             ENUM_HELPER(ImGuiTabBarFlags, FittingPolicyMask_),
             ENUM_HELPER(ImGuiTabBarFlags, FittingPolicyDefault_));
mod.new_enum("ImGuiTabItemFlags", ENUM_HELPER(ImGuiTabItemFlags, None),
             ENUM_HELPER(ImGuiTabItemFlags, UnsavedDocument),
             ENUM_HELPER(ImGuiTabItemFlags, SetSelected),
             ENUM_HELPER(ImGuiTabItemFlags, NoCloseWithMiddleMouseButton),
             ENUM_HELPER(ImGuiTabItemFlags, NoPushId),
             ENUM_HELPER(ImGuiTabItemFlags, NoTooltip),
             ENUM_HELPER(ImGuiTabItemFlags, NoReorder),
             ENUM_HELPER(ImGuiTabItemFlags, Leading),
             ENUM_HELPER(ImGuiTabItemFlags, Trailing),
             ENUM_HELPER(ImGuiTabItemFlags, NoAssumedClosure));
mod.new_enum("ImGuiFocusedFlags", ENUM_HELPER(ImGuiFocusedFlags, None),
             ENUM_HELPER(ImGuiFocusedFlags, ChildWindows),
             ENUM_HELPER(ImGuiFocusedFlags, RootWindow),
             ENUM_HELPER(ImGuiFocusedFlags, AnyWindow),
             ENUM_HELPER(ImGuiFocusedFlags, RootAndChildWindows));
mod.new_enum("ImGuiHoveredFlags", ENUM_HELPER(ImGuiHoveredFlags, None),
             ENUM_HELPER(ImGuiHoveredFlags, ChildWindows),
             ENUM_HELPER(ImGuiHoveredFlags, RootWindow),
             ENUM_HELPER(ImGuiHoveredFlags, AnyWindow),
             ENUM_HELPER(ImGuiHoveredFlags, NoPopupHierarchy),
             ENUM_HELPER(ImGuiHoveredFlags, DockHierarchy),
             ENUM_HELPER(ImGuiHoveredFlags, AllowWhenBlockedByPopup),
             ENUM_HELPER(ImGuiHoveredFlags, AllowWhenBlockedByActiveItem),
             ENUM_HELPER(ImGuiHoveredFlags, AllowWhenOverlappedByItem),
             ENUM_HELPER(ImGuiHoveredFlags, AllowWhenOverlappedByWindow),
             ENUM_HELPER(ImGuiHoveredFlags, AllowWhenDisabled),
             ENUM_HELPER(ImGuiHoveredFlags, NoNavOverride),
             ENUM_HELPER(ImGuiHoveredFlags, AllowWhenOverlapped),
             ENUM_HELPER(ImGuiHoveredFlags, RectOnly),
             ENUM_HELPER(ImGuiHoveredFlags, RootAndChildWindows),
             ENUM_HELPER(ImGuiHoveredFlags, ForTooltip),
             ENUM_HELPER(ImGuiHoveredFlags, Stationary),
             ENUM_HELPER(ImGuiHoveredFlags, DelayNone),
             ENUM_HELPER(ImGuiHoveredFlags, DelayShort),
             ENUM_HELPER(ImGuiHoveredFlags, DelayNormal),
             ENUM_HELPER(ImGuiHoveredFlags, NoSharedDelay));
mod.new_enum("ImGuiDockNodeFlags", ENUM_HELPER(ImGuiDockNodeFlags, None),
             ENUM_HELPER(ImGuiDockNodeFlags, KeepAliveOnly),
             ENUM_HELPER(ImGuiDockNodeFlags, NoDockingOverCentralNode),
             ENUM_HELPER(ImGuiDockNodeFlags, PassthruCentralNode),
             ENUM_HELPER(ImGuiDockNodeFlags, NoDockingSplit),
             ENUM_HELPER(ImGuiDockNodeFlags, NoResize),
             ENUM_HELPER(ImGuiDockNodeFlags, AutoHideTabBar),
             ENUM_HELPER(ImGuiDockNodeFlags, NoUndocking));
mod.new_enum("ImGuiDragDropFlags", ENUM_HELPER(ImGuiDragDropFlags, None),
             ENUM_HELPER(ImGuiDragDropFlags, SourceNoPreviewTooltip),
             ENUM_HELPER(ImGuiDragDropFlags, SourceNoDisableHover),
             ENUM_HELPER(ImGuiDragDropFlags, SourceNoHoldToOpenOthers),
             ENUM_HELPER(ImGuiDragDropFlags, SourceAllowNullID),
             ENUM_HELPER(ImGuiDragDropFlags, SourceExtern),
             ENUM_HELPER(ImGuiDragDropFlags, SourceAutoExpirePayload),
             ENUM_HELPER(ImGuiDragDropFlags, AcceptBeforeDelivery),
             ENUM_HELPER(ImGuiDragDropFlags, AcceptNoDrawDefaultRect),
             ENUM_HELPER(ImGuiDragDropFlags, AcceptNoPreviewTooltip),
             ENUM_HELPER(ImGuiDragDropFlags, AcceptPeekOnly));
mod.new_enum("ImGuiDataType", ENUM_HELPER(ImGuiDataType, S8),
             ENUM_HELPER(ImGuiDataType, U8), ENUM_HELPER(ImGuiDataType, S16),
             ENUM_HELPER(ImGuiDataType, U16), ENUM_HELPER(ImGuiDataType, S32),
             ENUM_HELPER(ImGuiDataType, U32), ENUM_HELPER(ImGuiDataType, S64),
             ENUM_HELPER(ImGuiDataType, U64), ENUM_HELPER(ImGuiDataType, Float),
             ENUM_HELPER(ImGuiDataType, Double),
             ENUM_HELPER(ImGuiDataType, COUNT));
mod.new_enum("ImGuiDir", ENUM_HELPER(ImGuiDir, None),
             ENUM_HELPER(ImGuiDir, Left), ENUM_HELPER(ImGuiDir, Right),
             ENUM_HELPER(ImGuiDir, Up), ENUM_HELPER(ImGuiDir, Down),
             ENUM_HELPER(ImGuiDir, COUNT));
mod.new_enum("ImGuiSortDirection", ENUM_HELPER(ImGuiSortDirection, None),
             ENUM_HELPER(ImGuiSortDirection, Ascending),
             ENUM_HELPER(ImGuiSortDirection, Descending));
mod.new_enum(
    "ImGuiKey", ENUM_HELPER(ImGuiKey, None), ENUM_HELPER(ImGuiKey, Tab),
    ENUM_HELPER(ImGuiKey, LeftArrow), ENUM_HELPER(ImGuiKey, RightArrow),
    ENUM_HELPER(ImGuiKey, UpArrow), ENUM_HELPER(ImGuiKey, DownArrow),
    ENUM_HELPER(ImGuiKey, PageUp), ENUM_HELPER(ImGuiKey, PageDown),
    ENUM_HELPER(ImGuiKey, Home), ENUM_HELPER(ImGuiKey, End),
    ENUM_HELPER(ImGuiKey, Insert), ENUM_HELPER(ImGuiKey, Delete),
    ENUM_HELPER(ImGuiKey, Backspace), ENUM_HELPER(ImGuiKey, Space),
    ENUM_HELPER(ImGuiKey, Enter), ENUM_HELPER(ImGuiKey, Escape),
    ENUM_HELPER(ImGuiKey, LeftCtrl), ENUM_HELPER(ImGuiKey, LeftShift),
    ENUM_HELPER(ImGuiKey, LeftAlt), ENUM_HELPER(ImGuiKey, LeftSuper),
    ENUM_HELPER(ImGuiKey, RightCtrl), ENUM_HELPER(ImGuiKey, RightShift),
    ENUM_HELPER(ImGuiKey, RightAlt), ENUM_HELPER(ImGuiKey, RightSuper),
    ENUM_HELPER(ImGuiKey, Menu), ENUM_HELPER(ImGuiKey, 0),
    ENUM_HELPER(ImGuiKey, 1), ENUM_HELPER(ImGuiKey, 2),
    ENUM_HELPER(ImGuiKey, 3), ENUM_HELPER(ImGuiKey, 4),
    ENUM_HELPER(ImGuiKey, 5), ENUM_HELPER(ImGuiKey, 6),
    ENUM_HELPER(ImGuiKey, 7), ENUM_HELPER(ImGuiKey, 8),
    ENUM_HELPER(ImGuiKey, 9), ENUM_HELPER(ImGuiKey, A),
    ENUM_HELPER(ImGuiKey, B), ENUM_HELPER(ImGuiKey, C),
    ENUM_HELPER(ImGuiKey, D), ENUM_HELPER(ImGuiKey, E),
    ENUM_HELPER(ImGuiKey, F), ENUM_HELPER(ImGuiKey, G),
    ENUM_HELPER(ImGuiKey, H), ENUM_HELPER(ImGuiKey, I),
    ENUM_HELPER(ImGuiKey, J), ENUM_HELPER(ImGuiKey, K),
    ENUM_HELPER(ImGuiKey, L), ENUM_HELPER(ImGuiKey, M),
    ENUM_HELPER(ImGuiKey, N), ENUM_HELPER(ImGuiKey, O),
    ENUM_HELPER(ImGuiKey, P), ENUM_HELPER(ImGuiKey, Q),
    ENUM_HELPER(ImGuiKey, R), ENUM_HELPER(ImGuiKey, S),
    ENUM_HELPER(ImGuiKey, T), ENUM_HELPER(ImGuiKey, U),
    ENUM_HELPER(ImGuiKey, V), ENUM_HELPER(ImGuiKey, W),
    ENUM_HELPER(ImGuiKey, X), ENUM_HELPER(ImGuiKey, Y),
    ENUM_HELPER(ImGuiKey, Z), ENUM_HELPER(ImGuiKey, F1),
    ENUM_HELPER(ImGuiKey, F2), ENUM_HELPER(ImGuiKey, F3),
    ENUM_HELPER(ImGuiKey, F4), ENUM_HELPER(ImGuiKey, F5),
    ENUM_HELPER(ImGuiKey, F6), ENUM_HELPER(ImGuiKey, F7),
    ENUM_HELPER(ImGuiKey, F8), ENUM_HELPER(ImGuiKey, F9),
    ENUM_HELPER(ImGuiKey, F10), ENUM_HELPER(ImGuiKey, F11),
    ENUM_HELPER(ImGuiKey, F12), ENUM_HELPER(ImGuiKey, F13),
    ENUM_HELPER(ImGuiKey, F14), ENUM_HELPER(ImGuiKey, F15),
    ENUM_HELPER(ImGuiKey, F16), ENUM_HELPER(ImGuiKey, F17),
    ENUM_HELPER(ImGuiKey, F18), ENUM_HELPER(ImGuiKey, F19),
    ENUM_HELPER(ImGuiKey, F20), ENUM_HELPER(ImGuiKey, F21),
    ENUM_HELPER(ImGuiKey, F22), ENUM_HELPER(ImGuiKey, F23),
    ENUM_HELPER(ImGuiKey, F24), ENUM_HELPER(ImGuiKey, Apostrophe),
    ENUM_HELPER(ImGuiKey, Comma), ENUM_HELPER(ImGuiKey, Minus),
    ENUM_HELPER(ImGuiKey, Period), ENUM_HELPER(ImGuiKey, Slash),
    ENUM_HELPER(ImGuiKey, Semicolon), ENUM_HELPER(ImGuiKey, Equal),
    ENUM_HELPER(ImGuiKey, LeftBracket), ENUM_HELPER(ImGuiKey, Backslash),
    ENUM_HELPER(ImGuiKey, RightBracket), ENUM_HELPER(ImGuiKey, GraveAccent),
    ENUM_HELPER(ImGuiKey, CapsLock), ENUM_HELPER(ImGuiKey, ScrollLock),
    ENUM_HELPER(ImGuiKey, NumLock), ENUM_HELPER(ImGuiKey, PrintScreen),
    ENUM_HELPER(ImGuiKey, Pause), ENUM_HELPER(ImGuiKey, Keypad0),
    ENUM_HELPER(ImGuiKey, Keypad1), ENUM_HELPER(ImGuiKey, Keypad2),
    ENUM_HELPER(ImGuiKey, Keypad3), ENUM_HELPER(ImGuiKey, Keypad4),
    ENUM_HELPER(ImGuiKey, Keypad5), ENUM_HELPER(ImGuiKey, Keypad6),
    ENUM_HELPER(ImGuiKey, Keypad7), ENUM_HELPER(ImGuiKey, Keypad8),
    ENUM_HELPER(ImGuiKey, Keypad9), ENUM_HELPER(ImGuiKey, KeypadDecimal),
    ENUM_HELPER(ImGuiKey, KeypadDivide), ENUM_HELPER(ImGuiKey, KeypadMultiply),
    ENUM_HELPER(ImGuiKey, KeypadSubtract), ENUM_HELPER(ImGuiKey, KeypadAdd),
    ENUM_HELPER(ImGuiKey, KeypadEnter), ENUM_HELPER(ImGuiKey, KeypadEqual),
    ENUM_HELPER(ImGuiKey, AppBack), ENUM_HELPER(ImGuiKey, AppForward),
    ENUM_HELPER(ImGuiKey, GamepadStart), ENUM_HELPER(ImGuiKey, GamepadBack),
    ENUM_HELPER(ImGuiKey, GamepadFaceLeft),
    ENUM_HELPER(ImGuiKey, GamepadFaceRight),
    ENUM_HELPER(ImGuiKey, GamepadFaceUp),
    ENUM_HELPER(ImGuiKey, GamepadFaceDown),
    ENUM_HELPER(ImGuiKey, GamepadDpadLeft),
    ENUM_HELPER(ImGuiKey, GamepadDpadRight),
    ENUM_HELPER(ImGuiKey, GamepadDpadUp),
    ENUM_HELPER(ImGuiKey, GamepadDpadDown), ENUM_HELPER(ImGuiKey, GamepadL1),
    ENUM_HELPER(ImGuiKey, GamepadR1), ENUM_HELPER(ImGuiKey, GamepadL2),
    ENUM_HELPER(ImGuiKey, GamepadR2), ENUM_HELPER(ImGuiKey, GamepadL3),
    ENUM_HELPER(ImGuiKey, GamepadR3), ENUM_HELPER(ImGuiKey, GamepadLStickLeft),
    ENUM_HELPER(ImGuiKey, GamepadLStickRight),
    ENUM_HELPER(ImGuiKey, GamepadLStickUp),
    ENUM_HELPER(ImGuiKey, GamepadLStickDown),
    ENUM_HELPER(ImGuiKey, GamepadRStickLeft),
    ENUM_HELPER(ImGuiKey, GamepadRStickRight),
    ENUM_HELPER(ImGuiKey, GamepadRStickUp),
    ENUM_HELPER(ImGuiKey, GamepadRStickDown), ENUM_HELPER(ImGuiKey, MouseLeft),
    ENUM_HELPER(ImGuiKey, MouseRight), ENUM_HELPER(ImGuiKey, MouseMiddle),
    ENUM_HELPER(ImGuiKey, MouseX1), ENUM_HELPER(ImGuiKey, MouseX2),
    ENUM_HELPER(ImGuiKey, MouseWheelX), ENUM_HELPER(ImGuiKey, MouseWheelY),
    ENUM_HELPER(ImGuiKey, ReservedForModCtrl),
    ENUM_HELPER(ImGuiKey, ReservedForModShift),
    ENUM_HELPER(ImGuiKey, ReservedForModAlt),
    ENUM_HELPER(ImGuiKey, ReservedForModSuper), ENUM_HELPER(ImGuiKey, COUNT),
    "Mod_None", ImGuiMod_None, "Mod_Ctrl", ImGuiMod_Ctrl, "Mod_Shift",
    ImGuiMod_Shift, "Mod_Alt", ImGuiMod_Alt, "Mod_Super", ImGuiMod_Super,
    "Mod_Mask_", ImGuiMod_Mask_, "NamedKey_BEGIN", ImGuiKey_NamedKey_BEGIN,
    "NamedKey_END", ImGuiKey_NamedKey_END, "NamedKey_COUNT",
    ImGuiKey_NamedKey_COUNT, "KeysData_SIZE", ImGuiKey_KeysData_SIZE,
    "KeysData_OFFSET", ImGuiKey_KeysData_OFFSET);
mod.new_enum("ImGuiInputFlags", ENUM_HELPER(ImGuiInputFlags, None),
             ENUM_HELPER(ImGuiInputFlags, Repeat),
             ENUM_HELPER(ImGuiInputFlags, RouteActive),
             ENUM_HELPER(ImGuiInputFlags, RouteFocused),
             ENUM_HELPER(ImGuiInputFlags, RouteGlobal),
             ENUM_HELPER(ImGuiInputFlags, RouteAlways),
             ENUM_HELPER(ImGuiInputFlags, RouteOverFocused),
             ENUM_HELPER(ImGuiInputFlags, RouteOverActive),
             ENUM_HELPER(ImGuiInputFlags, RouteUnlessBgFocused),
             ENUM_HELPER(ImGuiInputFlags, RouteFromRootWindow),
             ENUM_HELPER(ImGuiInputFlags, Tooltip));
mod.new_enum("ImGuiConfigFlags", ENUM_HELPER(ImGuiConfigFlags, None),
             ENUM_HELPER(ImGuiConfigFlags, NavEnableKeyboard),
             ENUM_HELPER(ImGuiConfigFlags, NavEnableGamepad),
             ENUM_HELPER(ImGuiConfigFlags, NavEnableSetMousePos),
             ENUM_HELPER(ImGuiConfigFlags, NavNoCaptureKeyboard),
             ENUM_HELPER(ImGuiConfigFlags, NoMouse),
             ENUM_HELPER(ImGuiConfigFlags, NoMouseCursorChange),
             ENUM_HELPER(ImGuiConfigFlags, DockingEnable),
             ENUM_HELPER(ImGuiConfigFlags, ViewportsEnable),
             ENUM_HELPER(ImGuiConfigFlags, DpiEnableScaleViewports),
             ENUM_HELPER(ImGuiConfigFlags, DpiEnableScaleFonts),
             ENUM_HELPER(ImGuiConfigFlags, IsSRGB),
             ENUM_HELPER(ImGuiConfigFlags, IsTouchScreen));
mod.new_enum("ImGuiBackendFlags", ENUM_HELPER(ImGuiBackendFlags, None),
             ENUM_HELPER(ImGuiBackendFlags, HasGamepad),
             ENUM_HELPER(ImGuiBackendFlags, HasMouseCursors),
             ENUM_HELPER(ImGuiBackendFlags, HasSetMousePos),
             ENUM_HELPER(ImGuiBackendFlags, RendererHasVtxOffset),
             ENUM_HELPER(ImGuiBackendFlags, PlatformHasViewports),
             ENUM_HELPER(ImGuiBackendFlags, HasMouseHoveredViewport),
             ENUM_HELPER(ImGuiBackendFlags, RendererHasViewports),
             ENUM_HELPER(ImGuiBackendFlags, PlatformHasViewports),
             ENUM_HELPER(ImGuiBackendFlags, RendererHasViewports));
mod.new_enum(
    "ImGuiCol", ENUM_HELPER(ImGuiCol, Text),
    ENUM_HELPER(ImGuiCol, TextDisabled), ENUM_HELPER(ImGuiCol, WindowBg),
    ENUM_HELPER(ImGuiCol, ChildBg), ENUM_HELPER(ImGuiCol, PopupBg),
    ENUM_HELPER(ImGuiCol, Border), ENUM_HELPER(ImGuiCol, BorderShadow),
    ENUM_HELPER(ImGuiCol, FrameBg), ENUM_HELPER(ImGuiCol, FrameBgHovered),
    ENUM_HELPER(ImGuiCol, FrameBgActive), ENUM_HELPER(ImGuiCol, TitleBg),
    ENUM_HELPER(ImGuiCol, TitleBgActive),
    ENUM_HELPER(ImGuiCol, TitleBgCollapsed), ENUM_HELPER(ImGuiCol, MenuBarBg),
    ENUM_HELPER(ImGuiCol, ScrollbarBg), ENUM_HELPER(ImGuiCol, ScrollbarGrab),
    ENUM_HELPER(ImGuiCol, ScrollbarGrabHovered),
    ENUM_HELPER(ImGuiCol, ScrollbarGrabActive),
    ENUM_HELPER(ImGuiCol, CheckMark), ENUM_HELPER(ImGuiCol, SliderGrab),
    ENUM_HELPER(ImGuiCol, SliderGrabActive), ENUM_HELPER(ImGuiCol, Button),
    ENUM_HELPER(ImGuiCol, ButtonHovered), ENUM_HELPER(ImGuiCol, ButtonActive),
    ENUM_HELPER(ImGuiCol, Header), ENUM_HELPER(ImGuiCol, HeaderHovered),
    ENUM_HELPER(ImGuiCol, HeaderActive), ENUM_HELPER(ImGuiCol, Separator),
    ENUM_HELPER(ImGuiCol, SeparatorHovered),
    ENUM_HELPER(ImGuiCol, SeparatorActive), ENUM_HELPER(ImGuiCol, ResizeGrip),
    ENUM_HELPER(ImGuiCol, ResizeGripHovered),
    ENUM_HELPER(ImGuiCol, ResizeGripActive), ENUM_HELPER(ImGuiCol, Tab),
    ENUM_HELPER(ImGuiCol, TabHovered), ENUM_HELPER(ImGuiCol, TabActive),
    ENUM_HELPER(ImGuiCol, TabUnfocused),
    ENUM_HELPER(ImGuiCol, TabUnfocusedActive), ENUM_HELPER(ImGuiCol, PlotLines),
    ENUM_HELPER(ImGuiCol, PlotLinesHovered),
    ENUM_HELPER(ImGuiCol, PlotHistogram),
    ENUM_HELPER(ImGuiCol, PlotHistogramHovered),
    ENUM_HELPER(ImGuiCol, TextSelectedBg),
    ENUM_HELPER(ImGuiCol, DragDropTarget), ENUM_HELPER(ImGuiCol, NavHighlight),
    ENUM_HELPER(ImGuiCol, NavWindowingHighlight),
    ENUM_HELPER(ImGuiCol, NavWindowingDimBg),
    ENUM_HELPER(ImGuiCol, ModalWindowDimBg), ENUM_HELPER(ImGuiCol, COUNT));
mod.new_enum("ImGuiStyleVar", ENUM_HELPER(ImGuiStyleVar, Alpha),
             ENUM_HELPER(ImGuiStyleVar, DisabledAlpha),
             ENUM_HELPER(ImGuiStyleVar, WindowPadding),
             ENUM_HELPER(ImGuiStyleVar, WindowRounding),
             ENUM_HELPER(ImGuiStyleVar, WindowBorderSize),
             ENUM_HELPER(ImGuiStyleVar, WindowMinSize),
             ENUM_HELPER(ImGuiStyleVar, WindowTitleAlign),
             ENUM_HELPER(ImGuiStyleVar, ChildRounding),
             ENUM_HELPER(ImGuiStyleVar, ChildBorderSize),
             ENUM_HELPER(ImGuiStyleVar, PopupRounding),
             ENUM_HELPER(ImGuiStyleVar, PopupBorderSize),
             ENUM_HELPER(ImGuiStyleVar, FramePadding),
             ENUM_HELPER(ImGuiStyleVar, FrameRounding),
             ENUM_HELPER(ImGuiStyleVar, FrameBorderSize),
             ENUM_HELPER(ImGuiStyleVar, ItemSpacing),
             ENUM_HELPER(ImGuiStyleVar, ItemInnerSpacing),
             ENUM_HELPER(ImGuiStyleVar, IndentSpacing),
             ENUM_HELPER(ImGuiStyleVar, CellPadding),
             ENUM_HELPER(ImGuiStyleVar, ScrollbarSize),
             ENUM_HELPER(ImGuiStyleVar, ScrollbarRounding),
             ENUM_HELPER(ImGuiStyleVar, GrabMinSize),
             ENUM_HELPER(ImGuiStyleVar, GrabRounding),
             ENUM_HELPER(ImGuiStyleVar, TabRounding),
             ENUM_HELPER(ImGuiStyleVar, TabBorderSize),
             ENUM_HELPER(ImGuiStyleVar, TabBarBorderSize),
             ENUM_HELPER(ImGuiStyleVar, TableAngledHeadersAngle),
             ENUM_HELPER(ImGuiStyleVar, TableAngledHeadersTextAlign),
             ENUM_HELPER(ImGuiStyleVar, ButtonTextAlign),
             ENUM_HELPER(ImGuiStyleVar, SelectableTextAlign),
             ENUM_HELPER(ImGuiStyleVar, SeparatorTextBorderSize),
             ENUM_HELPER(ImGuiStyleVar, SeparatorTextAlign),
             ENUM_HELPER(ImGuiStyleVar, SeparatorTextPadding),
             ENUM_HELPER(ImGuiStyleVar, DockingSeparatorSize),
             ENUM_HELPER(ImGuiStyleVar, COUNT));
mod.new_enum("ImGuiButtonFlags", ENUM_HELPER(ImGuiButtonFlags, None),
             ENUM_HELPER(ImGuiButtonFlags, MouseButtonLeft),
             ENUM_HELPER(ImGuiButtonFlags, MouseButtonRight),
             ENUM_HELPER(ImGuiButtonFlags, MouseButtonMiddle),
             ENUM_HELPER(ImGuiButtonFlags, MouseButtonMask_));
mod.new_enum("ImGuiColorEditFlags", ENUM_HELPER(ImGuiColorEditFlags, None),
             ENUM_HELPER(ImGuiColorEditFlags, NoAlpha),
             ENUM_HELPER(ImGuiColorEditFlags, NoPicker),
             ENUM_HELPER(ImGuiColorEditFlags, NoOptions),
             ENUM_HELPER(ImGuiColorEditFlags, NoSmallPreview),
             ENUM_HELPER(ImGuiColorEditFlags, NoInputs),
             ENUM_HELPER(ImGuiColorEditFlags, NoTooltip),
             ENUM_HELPER(ImGuiColorEditFlags, NoLabel),
             ENUM_HELPER(ImGuiColorEditFlags, NoSidePreview),
             ENUM_HELPER(ImGuiColorEditFlags, NoDragDrop),
             ENUM_HELPER(ImGuiColorEditFlags, NoBorder),
             ENUM_HELPER(ImGuiColorEditFlags, AlphaBar),
             ENUM_HELPER(ImGuiColorEditFlags, AlphaPreview),
             ENUM_HELPER(ImGuiColorEditFlags, AlphaPreviewHalf),
             ENUM_HELPER(ImGuiColorEditFlags, HDR),
             ENUM_HELPER(ImGuiColorEditFlags, DisplayRGB),
             ENUM_HELPER(ImGuiColorEditFlags, DisplayHSV),
             ENUM_HELPER(ImGuiColorEditFlags, DisplayHex),
             ENUM_HELPER(ImGuiColorEditFlags, Uint8),
             ENUM_HELPER(ImGuiColorEditFlags, Float),
             ENUM_HELPER(ImGuiColorEditFlags, PickerHueBar),
             ENUM_HELPER(ImGuiColorEditFlags, PickerHueWheel),
             ENUM_HELPER(ImGuiColorEditFlags, InputRGB),
             ENUM_HELPER(ImGuiColorEditFlags, InputHSV),
             ENUM_HELPER(ImGuiColorEditFlags, DefaultOptions_),
             ENUM_HELPER(ImGuiColorEditFlags, DisplayMask_),
             ENUM_HELPER(ImGuiColorEditFlags, DataTypeMask_),
             ENUM_HELPER(ImGuiColorEditFlags, PickerMask_),
             ENUM_HELPER(ImGuiColorEditFlags, InputMask_));
mod.new_enum("ImGuiSliderFlags", ENUM_HELPER(ImGuiSliderFlags, None),
             ENUM_HELPER(ImGuiSliderFlags, AlwaysClamp),
             ENUM_HELPER(ImGuiSliderFlags, Logarithmic),
             ENUM_HELPER(ImGuiSliderFlags, NoRoundToFormat),
             ENUM_HELPER(ImGuiSliderFlags, NoInput),
             ENUM_HELPER(ImGuiSliderFlags, InvalidMask_));
mod.new_enum("ImGuiMouseButton", ENUM_HELPER(ImGuiMouseButton, Left),
             ENUM_HELPER(ImGuiMouseButton, Right),
             ENUM_HELPER(ImGuiMouseButton, Middle),
             ENUM_HELPER(ImGuiMouseButton, COUNT));
mod.new_enum("ImGuiMouseCursor", ENUM_HELPER(ImGuiMouseCursor, None),
             ENUM_HELPER(ImGuiMouseCursor, Arrow),
             ENUM_HELPER(ImGuiMouseCursor, TextInput),
             ENUM_HELPER(ImGuiMouseCursor, ResizeAll),
             ENUM_HELPER(ImGuiMouseCursor, ResizeNS),
             ENUM_HELPER(ImGuiMouseCursor, ResizeEW),
             ENUM_HELPER(ImGuiMouseCursor, ResizeNESW),
             ENUM_HELPER(ImGuiMouseCursor, ResizeNWSE),
             ENUM_HELPER(ImGuiMouseCursor, Hand),
             ENUM_HELPER(ImGuiMouseCursor, NotAllowed),
             ENUM_HELPER(ImGuiMouseCursor, COUNT));
mod.new_enum("ImGuiMouseSource", ENUM_HELPER(ImGuiMouseSource, Mouse),
             ENUM_HELPER(ImGuiMouseSource, TouchScreen),
             ENUM_HELPER(ImGuiMouseSource, Pen),
             ENUM_HELPER(ImGuiMouseSource, COUNT));
mod.new_enum("ImGuiCond", ENUM_HELPER(ImGuiCond, None),
             ENUM_HELPER(ImGuiCond, Always), ENUM_HELPER(ImGuiCond, Once),
             ENUM_HELPER(ImGuiCond, FirstUseEver),
             ENUM_HELPER(ImGuiCond, Appearing));
mod.new_enum("ImGuiTableFlags", ENUM_HELPER(ImGuiTableFlags, None),
             ENUM_HELPER(ImGuiTableFlags, Resizable),
             ENUM_HELPER(ImGuiTableFlags, Reorderable),
             ENUM_HELPER(ImGuiTableFlags, Hideable),
             ENUM_HELPER(ImGuiTableFlags, Sortable),
             ENUM_HELPER(ImGuiTableFlags, NoSavedSettings),
             ENUM_HELPER(ImGuiTableFlags, ContextMenuInBody),
             ENUM_HELPER(ImGuiTableFlags, RowBg),
             ENUM_HELPER(ImGuiTableFlags, BordersInnerH),
             ENUM_HELPER(ImGuiTableFlags, BordersOuterH),
             ENUM_HELPER(ImGuiTableFlags, BordersInnerV),
             ENUM_HELPER(ImGuiTableFlags, BordersOuterV),
             ENUM_HELPER(ImGuiTableFlags, BordersH),
             ENUM_HELPER(ImGuiTableFlags, BordersV),
             ENUM_HELPER(ImGuiTableFlags, Borders),
             ENUM_HELPER(ImGuiTableFlags, BordersInner),
             ENUM_HELPER(ImGuiTableFlags, BordersOuter),
             ENUM_HELPER(ImGuiTableFlags, NoBordersInBody),
             ENUM_HELPER(ImGuiTableFlags, NoBordersInBodyUntilResize),
             ENUM_HELPER(ImGuiTableFlags, SizingFixedFit),
             ENUM_HELPER(ImGuiTableFlags, SizingFixedSame),
             ENUM_HELPER(ImGuiTableFlags, SizingStretchProp),
             ENUM_HELPER(ImGuiTableFlags, SizingStretchSame),
             ENUM_HELPER(ImGuiTableFlags, NoHostExtendX),
             ENUM_HELPER(ImGuiTableFlags, NoHostExtendY),
             ENUM_HELPER(ImGuiTableFlags, NoKeepColumnsVisible),
             ENUM_HELPER(ImGuiTableFlags, PreciseWidths),
             ENUM_HELPER(ImGuiTableFlags, NoClip),
             ENUM_HELPER(ImGuiTableFlags, PadOuterX),
             ENUM_HELPER(ImGuiTableFlags, NoPadOuterX),
             ENUM_HELPER(ImGuiTableFlags, NoPadInnerX),
             ENUM_HELPER(ImGuiTableFlags, ScrollX),
             ENUM_HELPER(ImGuiTableFlags, ScrollY),
             ENUM_HELPER(ImGuiTableFlags, SortMulti),
             ENUM_HELPER(ImGuiTableFlags, SortTristate),
             ENUM_HELPER(ImGuiTableFlags, HighlightHoveredColumn),
             ENUM_HELPER(ImGuiTableFlags, SizingMask_));
mod.new_enum("ImGuiTableColumnFlags", ENUM_HELPER(ImGuiTableColumnFlags, None),
             ENUM_HELPER(ImGuiTableColumnFlags, Disabled),
             ENUM_HELPER(ImGuiTableColumnFlags, DefaultHide),
             ENUM_HELPER(ImGuiTableColumnFlags, DefaultSort),
             ENUM_HELPER(ImGuiTableColumnFlags, WidthStretch),
             ENUM_HELPER(ImGuiTableColumnFlags, WidthFixed),
             ENUM_HELPER(ImGuiTableColumnFlags, NoResize),
             ENUM_HELPER(ImGuiTableColumnFlags, NoReorder),
             ENUM_HELPER(ImGuiTableColumnFlags, NoHide),
             ENUM_HELPER(ImGuiTableColumnFlags, NoClip),
             ENUM_HELPER(ImGuiTableColumnFlags, NoSort),
             ENUM_HELPER(ImGuiTableColumnFlags, NoSortAscending),
             ENUM_HELPER(ImGuiTableColumnFlags, NoSortDescending),
             ENUM_HELPER(ImGuiTableColumnFlags, NoHeaderLabel),
             ENUM_HELPER(ImGuiTableColumnFlags, NoHeaderWidth),
             ENUM_HELPER(ImGuiTableColumnFlags, PreferSortAscending),
             ENUM_HELPER(ImGuiTableColumnFlags, PreferSortDescending),
             ENUM_HELPER(ImGuiTableColumnFlags, IndentEnable),
             ENUM_HELPER(ImGuiTableColumnFlags, IndentDisable),
             ENUM_HELPER(ImGuiTableColumnFlags, IsEnabled),
             ENUM_HELPER(ImGuiTableColumnFlags, IsVisible),
             ENUM_HELPER(ImGuiTableColumnFlags, IsSorted),
             ENUM_HELPER(ImGuiTableColumnFlags, IsHovered),
             ENUM_HELPER(ImGuiTableColumnFlags, WidthMask_),
             ENUM_HELPER(ImGuiTableColumnFlags, IndentMask_),
             ENUM_HELPER(ImGuiTableColumnFlags, StatusMask_));
mod.new_enum("ImGuiTableRowFlags", ENUM_HELPER(ImGuiTableRowFlags, None),
             ENUM_HELPER(ImGuiTableRowFlags, Headers));
mod.new_enum("ImGuiTableBgTarget", ENUM_HELPER(ImGuiTableBgTarget, None),
             ENUM_HELPER(ImGuiTableBgTarget, RowBg0),
             ENUM_HELPER(ImGuiTableBgTarget, RowBg1),
             ENUM_HELPER(ImGuiTableBgTarget, CellBg));
mod.new_enum("ImDrawFlags", ENUM_HELPER(ImDrawFlags, None),
             ENUM_HELPER(ImDrawFlags, Closed),
             ENUM_HELPER(ImDrawFlags, RoundCornersTopLeft),
             ENUM_HELPER(ImDrawFlags, RoundCornersTopRight),
             ENUM_HELPER(ImDrawFlags, RoundCornersBottomLeft),
             ENUM_HELPER(ImDrawFlags, RoundCornersBottomRight),
             ENUM_HELPER(ImDrawFlags, RoundCornersTop),
             ENUM_HELPER(ImDrawFlags, RoundCornersBottom),
             ENUM_HELPER(ImDrawFlags, RoundCornersLeft),
             ENUM_HELPER(ImDrawFlags, RoundCornersRight),
             ENUM_HELPER(ImDrawFlags, RoundCornersAll),
             ENUM_HELPER(ImDrawFlags, RoundCornersNone),
             ENUM_HELPER(ImDrawFlags, RoundCornersDefault_),
             ENUM_HELPER(ImDrawFlags, RoundCornersMask_));
mod.new_enum("ImDrawListFlags", ENUM_HELPER(ImDrawListFlags, None),
             ENUM_HELPER(ImDrawListFlags, AntiAliasedLines),
             ENUM_HELPER(ImDrawListFlags, AntiAliasedLinesUseTex),
             ENUM_HELPER(ImDrawListFlags, AntiAliasedFill),
             ENUM_HELPER(ImDrawListFlags, AllowVtxOffset));
mod.new_enum("ImFontAtlasFlags", ENUM_HELPER(ImFontAtlasFlags, None),
             ENUM_HELPER(ImFontAtlasFlags, NoPowerOfTwoHeight),
             ENUM_HELPER(ImFontAtlasFlags, NoMouseCursors),
             ENUM_HELPER(ImFontAtlasFlags, NoBakedLines));
mod.new_enum("ImGuiViewportFlags", ENUM_HELPER(ImGuiViewportFlags, None),
             ENUM_HELPER(ImGuiViewportFlags, IsPlatformWindow),
             ENUM_HELPER(ImGuiViewportFlags, IsPlatformMonitor),
             ENUM_HELPER(ImGuiViewportFlags, OwnedByApp),
             ENUM_HELPER(ImGuiViewportFlags, NoDecoration),
             ENUM_HELPER(ImGuiViewportFlags, NoTaskBarIcon),
             ENUM_HELPER(ImGuiViewportFlags, NoFocusOnAppearing),
             ENUM_HELPER(ImGuiViewportFlags, NoFocusOnClick),
             ENUM_HELPER(ImGuiViewportFlags, NoInputs),
             ENUM_HELPER(ImGuiViewportFlags, NoRendererClear),
             ENUM_HELPER(ImGuiViewportFlags, NoAutoMerge),
             ENUM_HELPER(ImGuiViewportFlags, TopMost),
             ENUM_HELPER(ImGuiViewportFlags, CanHostOtherWindows),
             ENUM_HELPER(ImGuiViewportFlags, IsMinimized),
             ENUM_HELPER(ImGuiViewportFlags, IsFocused));
mod.new_enum("ImGuiItemFlags", ENUM_HELPER(ImGuiItemFlags, None),
             ENUM_HELPER(ImGuiItemFlags, NoTabStop),
             ENUM_HELPER(ImGuiItemFlags, ButtonRepeat),
             ENUM_HELPER(ImGuiItemFlags, Disabled),
             ENUM_HELPER(ImGuiItemFlags, NoNav),
             ENUM_HELPER(ImGuiItemFlags, NoNavDefaultFocus),
             ENUM_HELPER(ImGuiItemFlags, SelectableDontClosePopup),
             ENUM_HELPER(ImGuiItemFlags, MixedValue),
             ENUM_HELPER(ImGuiItemFlags, ReadOnly),
             ENUM_HELPER(ImGuiItemFlags, NoWindowHoverableCheck),
             ENUM_HELPER(ImGuiItemFlags, AllowOverlap),
             ENUM_HELPER(ImGuiItemFlags, Inputable),
             ENUM_HELPER(ImGuiItemFlags, HasSelectionUserData));
mod.new_enum("ImGuiItemStatusFlags", ENUM_HELPER(ImGuiItemStatusFlags, None),
             ENUM_HELPER(ImGuiItemStatusFlags, HoveredRect),
             ENUM_HELPER(ImGuiItemStatusFlags, HasDisplayRect),
             ENUM_HELPER(ImGuiItemStatusFlags, Edited),
             ENUM_HELPER(ImGuiItemStatusFlags, ToggledSelection),
             ENUM_HELPER(ImGuiItemStatusFlags, ToggledOpen),
             ENUM_HELPER(ImGuiItemStatusFlags, HasDeactivated),
             ENUM_HELPER(ImGuiItemStatusFlags, Deactivated),
             ENUM_HELPER(ImGuiItemStatusFlags, HoveredWindow),
             ENUM_HELPER(ImGuiItemStatusFlags, Visible),
             ENUM_HELPER(ImGuiItemStatusFlags, HasClipRect),
             ENUM_HELPER(ImGuiItemStatusFlags, HasShortcut));
mod.new_enum("ImGuiHoveredFlagsPrivate",
             ENUM_HELPER(ImGuiHoveredFlags, DelayMask_),
             ENUM_HELPER(ImGuiHoveredFlags, AllowedMaskForIsWindowHovered),
             ENUM_HELPER(ImGuiHoveredFlags, AllowedMaskForIsItemHovered));
mod.new_enum("ImGuiInputTextFlagsPrivate",
             ENUM_HELPER(ImGuiInputTextFlags, Multiline),
             ENUM_HELPER(ImGuiInputTextFlags, NoMarkEdited),
             ENUM_HELPER(ImGuiInputTextFlags, MergedItem),
             ENUM_HELPER(ImGuiInputTextFlags, LocalizeDecimalPoint));
mod.new_enum("ImGuiButtonFlagsPrivate",
             ENUM_HELPER(ImGuiButtonFlags, PressedOnClick),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnClickRelease),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnClickReleaseAnywhere),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnRelease),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnDoubleClick),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnDragDropHold),
             ENUM_HELPER(ImGuiButtonFlags, Repeat),
             ENUM_HELPER(ImGuiButtonFlags, FlattenChildren),
             ENUM_HELPER(ImGuiButtonFlags, AllowOverlap),
             ENUM_HELPER(ImGuiButtonFlags, DontClosePopups),
             ENUM_HELPER(ImGuiButtonFlags, AlignTextBaseLine),
             ENUM_HELPER(ImGuiButtonFlags, NoKeyModifiers),
             ENUM_HELPER(ImGuiButtonFlags, NoHoldingActiveId),
             ENUM_HELPER(ImGuiButtonFlags, NoNavFocus),
             ENUM_HELPER(ImGuiButtonFlags, NoHoveredOnFocus),
             ENUM_HELPER(ImGuiButtonFlags, NoSetKeyOwner),
             ENUM_HELPER(ImGuiButtonFlags, NoTestKeyOwner),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnMask_),
             ENUM_HELPER(ImGuiButtonFlags, PressedOnDefault_));
mod.new_enum("ImGuiComboFlagsPrivate",
             ENUM_HELPER(ImGuiComboFlags, CustomPreview));
mod.new_enum("ImGuiSliderFlagsPrivate", ENUM_HELPER(ImGuiSliderFlags, Vertical),
             ENUM_HELPER(ImGuiSliderFlags, ReadOnly));
mod.new_enum("ImGuiSelectableFlagsPrivate",
             ENUM_HELPER(ImGuiSelectableFlags, NoHoldingActiveID),
             ENUM_HELPER(ImGuiSelectableFlags, SelectOnNav),
             ENUM_HELPER(ImGuiSelectableFlags, SelectOnClick),
             ENUM_HELPER(ImGuiSelectableFlags, SelectOnRelease),
             ENUM_HELPER(ImGuiSelectableFlags, SpanAvailWidth),
             ENUM_HELPER(ImGuiSelectableFlags, SetNavIdOnHover),
             ENUM_HELPER(ImGuiSelectableFlags, NoPadWithHalfSpacing),
             ENUM_HELPER(ImGuiSelectableFlags, NoSetKeyOwner));
mod.new_enum("ImGuiTreeNodeFlagsPrivate",
             ENUM_HELPER(ImGuiTreeNodeFlags, ClipLabelForTrailingButton),
             ENUM_HELPER(ImGuiTreeNodeFlags, UpsideDownArrow));
mod.new_enum("ImGuiSeparatorFlagsPrivate",
             ENUM_HELPER(ImGuiSeparatorFlags, None),
             ENUM_HELPER(ImGuiSeparatorFlags, Horizontal),
             ENUM_HELPER(ImGuiSeparatorFlags, Vertical),
             ENUM_HELPER(ImGuiSeparatorFlags, SpanAllColumns));
mod.new_enum("ImGuiFocusRequestFlags",
             ENUM_HELPER(ImGuiFocusRequestFlags, None),
             ENUM_HELPER(ImGuiFocusRequestFlags, RestoreFocusedChild),
             ENUM_HELPER(ImGuiFocusRequestFlags, UnlessBelowModal));
mod.new_enum("ImGuiTextFlags", ENUM_HELPER(ImGuiTextFlags, None),
             ENUM_HELPER(ImGuiTextFlags, NoWidthForLargeClippedText));
mod.new_enum("ImGuiTooltipFlags", ENUM_HELPER(ImGuiTooltipFlags, None),
             ENUM_HELPER(ImGuiTooltipFlags, OverridePrevious));
mod.new_enum("ImGuiLayoutType", ENUM_HELPER(ImGuiLayoutType, Vertical),
             ENUM_HELPER(ImGuiLayoutType, Horizontal));
mod.new_enum("ImGuiLogType", ENUM_HELPER(ImGuiLogType, None),
             ENUM_HELPER(ImGuiLogType, TTY), ENUM_HELPER(ImGuiLogType, File),
             ENUM_HELPER(ImGuiLogType, Buffer),
             ENUM_HELPER(ImGuiLogType, Clipboard));
mod.new_enum("ImGuiAxis", ENUM_HELPER(ImGuiAxis, None),
             ENUM_HELPER(ImGuiAxis, X), ENUM_HELPER(ImGuiAxis, Y));
mod.new_enum("ImGuiPlotType", ENUM_HELPER(ImGuiPlotType, Lines),
             ENUM_HELPER(ImGuiPlotType, Histogram));
mod.new_enum("ImGuiWindowRefreshFlags",
             ENUM_HELPER(ImGuiWindowRefreshFlags, None),
             ENUM_HELPER(ImGuiWindowRefreshFlags, TryToAvoidRefresh),
             ENUM_HELPER(ImGuiWindowRefreshFlags, RefreshOnHover),
             ENUM_HELPER(ImGuiWindowRefreshFlags, RefreshOnFocus));
mod.new_enum("ImGuiNextWindowDataFlags",
             ENUM_HELPER(ImGuiNextWindowDataFlags, None),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasPos),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasSize),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasContentSize),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasCollapsed),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasSizeConstraint),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasFocus),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasBgAlpha),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasScroll),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasViewport),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasDock),
             ENUM_HELPER(ImGuiNextWindowDataFlags, HasWindowClass));
mod.new_enum("ImGuiNextItemDataFlags",
             ENUM_HELPER(ImGuiNextItemDataFlags, None),
             ENUM_HELPER(ImGuiNextItemDataFlags, HasWidth),
             ENUM_HELPER(ImGuiNextItemDataFlags, HasOpen),
             ENUM_HELPER(ImGuiNextItemDataFlags, HasShortcut),
             ENUM_HELPER(ImGuiNextItemDataFlags, HasRefVal));
mod.new_enum("ImGuiInputEventType", ENUM_HELPER(ImGuiInputEventType, Key),
             ENUM_HELPER(ImGuiInputEventType, MousePos),
             ENUM_HELPER(ImGuiInputEventType, MouseWheel),
             ENUM_HELPER(ImGuiInputEventType, MouseButton),
             ENUM_HELPER(ImGuiInputEventType, MouseViewport),
             ENUM_HELPER(ImGuiInputEventType, Key),
             ENUM_HELPER(ImGuiInputEventType, Text),
             ENUM_HELPER(ImGuiInputEventType, Focus),
             ENUM_HELPER(ImGuiInputEventType, COUNT));
mod.new_enum("ImGuiInputSource", ENUM_HELPER(ImGuiInputSource, None),
             ENUM_HELPER(ImGuiInputSource, Mouse),
             ENUM_HELPER(ImGuiInputSource, Keyboard),
             ENUM_HELPER(ImGuiInputSource, Gamepad),
             ENUM_HELPER(ImGuiInputSource, COUNT));
mod.new_enum("ImGuiInputFlagsPrivate",
             ENUM_HELPER(ImGuiInputFlags, RepeatRateDefault),
             ENUM_HELPER(ImGuiInputFlags, RepeatRateNavMove),
             ENUM_HELPER(ImGuiInputFlags, RepeatRateNavTweak),
             ENUM_HELPER(ImGuiInputFlags, RepeatUntilRelease),
             ENUM_HELPER(ImGuiInputFlags, RepeatUntilKeyModsChange),
             ENUM_HELPER(ImGuiInputFlags, RepeatUntilKeyModsChangeFromNone),
             ENUM_HELPER(ImGuiInputFlags, LockThisFrame),
             ENUM_HELPER(ImGuiInputFlags, LockUntilRelease),
             ENUM_HELPER(ImGuiInputFlags, CondHovered),
             ENUM_HELPER(ImGuiInputFlags, CondActive),
             ENUM_HELPER(ImGuiInputFlags, CondDefault_),
             ENUM_HELPER(ImGuiInputFlags, RepeatRateMask_),
             ENUM_HELPER(ImGuiInputFlags, RepeatMask_),
             ENUM_HELPER(ImGuiInputFlags, CondMask_),
             ENUM_HELPER(ImGuiInputFlags, RouteTypeMask_),
             ENUM_HELPER(ImGuiInputFlags, RouteOptionsMask_),
             ENUM_HELPER(ImGuiInputFlags, SupportedByIsKeyPressed),
             ENUM_HELPER(ImGuiInputFlags, SupportedByIsMouseClicked),
             ENUM_HELPER(ImGuiInputFlags, SupportedByShortcut),
             ENUM_HELPER(ImGuiInputFlags, SupportedBySetNextItemShortcut),
             ENUM_HELPER(ImGuiInputFlags, SupportedBySetKeyOwner),
             ENUM_HELPER(ImGuiInputFlags, SupportedBySetItemKeyOwner));
mod.new_enum("ImGuiActivateFlags", ENUM_HELPER(ImGuiActivateFlags, None),
             ENUM_HELPER(ImGuiActivateFlags, PreferInput),
             ENUM_HELPER(ImGuiActivateFlags, PreferTweak),
             ENUM_HELPER(ImGuiActivateFlags, TryToPreserveState),
             ENUM_HELPER(ImGuiActivateFlags, FromTabbing),
             ENUM_HELPER(ImGuiActivateFlags, FromShortcut));
mod.new_enum("ImGuiScrollFlags", ENUM_HELPER(ImGuiScrollFlags, None),
             ENUM_HELPER(ImGuiScrollFlags, KeepVisibleEdgeX),
             ENUM_HELPER(ImGuiScrollFlags, KeepVisibleEdgeY),
             ENUM_HELPER(ImGuiScrollFlags, KeepVisibleCenterX),
             ENUM_HELPER(ImGuiScrollFlags, KeepVisibleCenterY),
             ENUM_HELPER(ImGuiScrollFlags, AlwaysCenterX),
             ENUM_HELPER(ImGuiScrollFlags, AlwaysCenterY),
             ENUM_HELPER(ImGuiScrollFlags, NoScrollParent),
             ENUM_HELPER(ImGuiScrollFlags, MaskX_),
             ENUM_HELPER(ImGuiScrollFlags, MaskY_));
mod.new_enum("ImGuiNavHighlightFlags",
             ENUM_HELPER(ImGuiNavHighlightFlags, None),
             ENUM_HELPER(ImGuiNavHighlightFlags, Compact),
             ENUM_HELPER(ImGuiNavHighlightFlags, AlwaysDraw),
             ENUM_HELPER(ImGuiNavHighlightFlags, NoRounding));
mod.new_enum("ImGuiNavMoveFlags", ENUM_HELPER(ImGuiNavMoveFlags, None),
             ENUM_HELPER(ImGuiNavMoveFlags, LoopX),
             ENUM_HELPER(ImGuiNavMoveFlags, LoopY),
             ENUM_HELPER(ImGuiNavMoveFlags, WrapX),
             ENUM_HELPER(ImGuiNavMoveFlags, WrapY),
             ENUM_HELPER(ImGuiNavMoveFlags, WrapMask_),
             ENUM_HELPER(ImGuiNavMoveFlags, AllowCurrentNavId),
             ENUM_HELPER(ImGuiNavMoveFlags, AlsoScoreVisibleSet),
             ENUM_HELPER(ImGuiNavMoveFlags, ScrollToEdgeY),
             ENUM_HELPER(ImGuiNavMoveFlags, Forwarded),
             ENUM_HELPER(ImGuiNavMoveFlags, DebugNoResult),
             ENUM_HELPER(ImGuiNavMoveFlags, FocusApi),
             ENUM_HELPER(ImGuiNavMoveFlags, IsTabbing),
             ENUM_HELPER(ImGuiNavMoveFlags, IsPageMove),
             ENUM_HELPER(ImGuiNavMoveFlags, Activate),
             ENUM_HELPER(ImGuiNavMoveFlags, NoSelect),
             ENUM_HELPER(ImGuiNavMoveFlags, NoSetNavHighlight),
             ENUM_HELPER(ImGuiNavMoveFlags, NoClearActiveId));
mod.new_enum("ImGuiNavItemData", "NavLayer_Main", ImGuiNavLayer_Main,
             "NavLayer_Menu", ImGuiNavLayer_Menu, "NavLayer_COUNT",
             ImGuiNavLayer_COUNT);
mod.new_enum("ImGuiTypingSelectFlags",
             ENUM_HELPER(ImGuiTypingSelectFlags, None),
             ENUM_HELPER(ImGuiTypingSelectFlags, AllowBackspace),
             ENUM_HELPER(ImGuiTypingSelectFlags, AllowSingleCharMode));
mod.new_enum("ImGuidOldColumnFlags", ENUM_HELPER(ImGuiOldColumnFlags, None),
             ENUM_HELPER(ImGuiOldColumnFlags, NoBorder),
             ENUM_HELPER(ImGuiOldColumnFlags, NoResize),
             ENUM_HELPER(ImGuiOldColumnFlags, NoPreserveWidths),
             ENUM_HELPER(ImGuiOldColumnFlags, NoForceWithinWindow),
             ENUM_HELPER(ImGuiOldColumnFlags, GrowParentContentsSize),
             ENUM_HELPER(ImGuiOldColumnFlags, GrowParentContentsSize));
mod.new_enum("ImGuiDataAuthority", ENUM_HELPER(ImGuiDataAuthority, Auto),
             ENUM_HELPER(ImGuiDataAuthority, DockNode),
             ENUM_HELPER(ImGuiDataAuthority, Window));
mod.new_enum("ImGuiDockNodeState", ENUM_HELPER(ImGuiDockNodeState, Unknown),
             ENUM_HELPER(ImGuiDockNodeState,
                         HostWindowHiddenBecauseSingleWindow),
             ENUM_HELPER(ImGuiDockNodeState,
                         HostWindowHiddenBecauseWindowsAreResizing),
             ENUM_HELPER(ImGuiDockNodeState, HostWindowVisible));
mod.new_enum("ImGuiWindowDockStyleCol",
             ENUM_HELPER(ImGuiWindowDockStyleCol, Text),
             ENUM_HELPER(ImGuiWindowDockStyleCol, Tab),
             ENUM_HELPER(ImGuiWindowDockStyleCol, TabHovered),
             ENUM_HELPER(ImGuiWindowDockStyleCol, TabActive),
             ENUM_HELPER(ImGuiWindowDockStyleCol, TabUnfocused),
             ENUM_HELPER(ImGuiWindowDockStyleCol, TabUnfocusedActive),
             ENUM_HELPER(ImGuiWindowDockStyleCol, COUNT));
mod.new_enum("ImGuiLocKey", ENUM_HELPER(ImGuiLocKey, VersionStr),
             ENUM_HELPER(ImGuiLocKey, TableSizeOne),
             ENUM_HELPER(ImGuiLocKey, TableSizeAllFit),
             ENUM_HELPER(ImGuiLocKey, TableSizeAllDefault),
             ENUM_HELPER(ImGuiLocKey, TableResetOrder),
             ENUM_HELPER(ImGuiLocKey, WindowingMainMenuBar),
             ENUM_HELPER(ImGuiLocKey, WindowingPopup),
             ENUM_HELPER(ImGuiLocKey, WindowingUntitled),
             ENUM_HELPER(ImGuiLocKey, DockingHideTabBar),
             ENUM_HELPER(ImGuiLocKey, DockingHoldShiftToDock),
             ENUM_HELPER(ImGuiLocKey, DockingDragToUndockOrMoveNode),
             ENUM_HELPER(ImGuiLocKey, COUNT));
mod.new_enum("ImGuiDebugLogFlags", ENUM_HELPER(ImGuiDebugLogFlags, None),
             ENUM_HELPER(ImGuiDebugLogFlags, EventActiveId),
             ENUM_HELPER(ImGuiDebugLogFlags, EventFocus),
             ENUM_HELPER(ImGuiDebugLogFlags, EventPopup),
             ENUM_HELPER(ImGuiDebugLogFlags, EventNav),
             ENUM_HELPER(ImGuiDebugLogFlags, EventClipper),
             ENUM_HELPER(ImGuiDebugLogFlags, EventSelection),
             ENUM_HELPER(ImGuiDebugLogFlags, EventIO),
             ENUM_HELPER(ImGuiDebugLogFlags, EventInputRouting),
             ENUM_HELPER(ImGuiDebugLogFlags, EventDocking),
             ENUM_HELPER(ImGuiDebugLogFlags, EventViewport),
             ENUM_HELPER(ImGuiDebugLogFlags, EventMask_),
             ENUM_HELPER(ImGuiDebugLogFlags, OutputToTTY),
             ENUM_HELPER(ImGuiDebugLogFlags, OutputToTestEngine));
mod.new_enum("ImGuiContextHookType",
             ENUM_HELPER(ImGuiContextHookType, NewFramePre),
             ENUM_HELPER(ImGuiContextHookType, NewFramePost),
             ENUM_HELPER(ImGuiContextHookType, EndFramePre),
             ENUM_HELPER(ImGuiContextHookType, EndFramePost),
             ENUM_HELPER(ImGuiContextHookType, RenderPre),
             ENUM_HELPER(ImGuiContextHookType, RenderPost),
             ENUM_HELPER(ImGuiContextHookType, Shutdown),
             ENUM_HELPER(ImGuiContextHookType, PendingRemoval_));
mod.new_enum("ImGuiTabBarFlagsPrivate", ENUM_HELPER(ImGuiTabBarFlags, DockNode),
             ENUM_HELPER(ImGuiTabBarFlags, IsFocused),
             ENUM_HELPER(ImGuiTabBarFlags, SaveSettings));
mod.new_enum("ImGuiTabItemFlagsPrivate",
             ENUM_HELPER(ImGuiTabItemFlags, SectionMask_),
             ENUM_HELPER(ImGuiTabItemFlags, NoCloseButton),
             ENUM_HELPER(ImGuiTabItemFlags, Button),
             ENUM_HELPER(ImGuiTabItemFlags, Unsorted));

#pragma endregion

}