describe('path spec', function()
  describe('getprefix', function()
    it([[returns the drive letter for a Windows path]], function()
      local path = require('path')
      assert.are.equal('C:', path.getprefix [[C:\Windows\System32\cmd.exe]])
    end)
  end)

  describe('split', function()
    it([[splits a path into an expected table]], function()
      local path = require('path')
      local parts = path.split [[C:\Windows\System32\cmd.exe]]
      assert.are.same(parts, { 'C:', 'Windows', 'System32', 'cmd.exe' })
    end)
    it([[splits a path with varying separators]], function()
      local path = require('path')
      local parts = path.split [[C:/Windows\System32/cmd.exe]]
      assert.are.same(parts, { 'C:', 'Windows', 'System32', 'cmd.exe' })
    end)
  end)

  describe('join', function()
    it([[joins a table of path segments into a path]], function()
      local path = require('path')
      assert.are.equal([[C:\Windows\System32\cmd.exe]], path.join('C:', 'Windows', 'System32', 'cmd.exe'))
    end)

    it([[joins a table and resolves to the normalized path]], function()
      local path = require('path')
      assert.are.equal([[C:\Windows\cmd.exe]], path.join('C:', 'Windows', 'System32', '..', 'cmd.exe'))
    end)

    it([[resolves to the root when too many parent directories are given]], function()
      local path = require('path')
      assert.are.equal([[C:\cmd.exe]], path.join('C:', 'Windows', 'System32', '..', '..', '..', 'cmd.exe'))
    end)
  end)

  describe('dirsep', function()
    it([[chooses \ as the directory separator for Windows]], function()
      local path = require('path')
      assert.are.equal('\\', path.dirsep)
    end)
  end)
  describe('isrelative', function()
    it([[returns true for a relative path]], function()
      local path = require('path')
      assert(path.isrelative [[Windows\System32\cmd.exe]])
    end)
    it([[returns false for an absolute path]], function()
      local path = require('path')
      assert(not path.isrelative [[C:\Windows\System32\cmd.exe]])
    end)
  end)
  describe('isabsolute', function()
    it([[returns false for a relative path]], function()
      local path = require('path')
      assert(not path.isabsolute [[Windows\System32\cmd.exe]])
    end)
    it([[returns true for an absolute path]], function()
      local path = require('path')
      assert(path.isabsolute [[C:\Windows\System32\cmd.exe]])
    end)
  end)
end)
