describe('stringsplit spec', function()
  it('splits a string into a table of strings', function()
    local stringsplit = require('stringsplit')
    local parts = stringsplit('a,b,c', ',')
    assert.are.same({ 'a', 'b', 'c' }, parts)
  end)
  it('splits a string into a table of strings with a different separator', function()
    local stringsplit = require('stringsplit')
    local parts = stringsplit('a b c', ' ')
    assert.are.same({ 'a', 'b', 'c' }, parts)
  end)
end)
